# Generated by Django 4.1.7 on 2023-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_modell_delete_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='mo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('ligne', models.IntegerField()),
            ],
        ),
    ]
