# Generated by Django 4.1.7 on 2023-03-16 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_mansour'),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.mansour')),
            ],
        ),
    ]
