# Generated by Django 4.1.7 on 2023-03-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_delete_aa_delete_bb_remove_file_id_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mo',
        ),
        migrations.DeleteModel(
            name='modell',
        ),
    ]
