# Generated by Django 4.1.7 on 2023-03-16 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_delete_mo_delete_modell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mansour',
        ),
    ]
