# Generated by Django 4.1.7 on 2023-03-16 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_delete_mansour'),
    ]

    operations = [
        migrations.CreateModel(
            name='mansour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('ligne', models.IntegerField()),
                ('id_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.file')),
            ],
        ),
    ]
