# Generated by Django 4.1.7 on 2023-03-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0013_lignemodifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=50, null=True)),
                ('designation_article', models.CharField(blank=True, max_length=50, null=True)),
                ('text_article', models.CharField(blank=True, max_length=50, null=True)),
                ('grpe_march', models.CharField(blank=True, max_length=50, null=True)),
                ('div', models.CharField(blank=True, max_length=50, null=True)),
                ('ctrpr', models.CharField(blank=True, max_length=50, null=True)),
                ('typ_app', models.CharField(blank=True, max_length=50, null=True)),
                ('a_s', models.CharField(blank=True, max_length=50, null=True)),
                ('tcy', models.CharField(blank=True, max_length=50, null=True)),
                ('dfi', models.CharField(blank=True, max_length=50, null=True)),
                ('dpr', models.CharField(blank=True, max_length=50, null=True)),
                ('horiz', models.CharField(blank=True, max_length=50, null=True)),
                ('mp', models.CharField(blank=True, max_length=50, null=True)),
                ('r', models.CharField(blank=True, max_length=50, null=True)),
                ('tyar', models.CharField(blank=True, max_length=50, null=True)),
                ('nal', models.CharField(blank=True, max_length=50, null=True)),
                ('i_c', models.CharField(blank=True, max_length=50, null=True)),
                ('aappr_def', models.CharField(blank=True, max_length=50, null=True)),
                ('mgapp', models.CharField(blank=True, max_length=50, null=True)),
                ('mag', models.CharField(blank=True, max_length=50, null=True)),
                ('tl', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_fixe', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_securite', models.CharField(blank=True, max_length=50, null=True)),
                ('tre', models.CharField(blank=True, max_length=50, null=True)),
                ('gest', models.CharField(blank=True, max_length=50, null=True)),
                ('di', models.CharField(blank=True, max_length=50, null=True)),
                ('rebut', models.CharField(blank=True, max_length=50, null=True)),
                ('gac', models.CharField(blank=True, max_length=50, null=True)),
                ('Profil', models.CharField(blank=True, max_length=50, null=True)),
                ('prpiAt', models.CharField(blank=True, max_length=50, null=True)),
                ('cree_par', models.CharField(blank=True, max_length=50, null=True)),
                ('langue', models.CharField(blank=True, max_length=50, null=True)),
                ('Cree_le', models.CharField(blank=True, max_length=50, null=True)),
                ('gcha', models.CharField(blank=True, max_length=50, null=True)),
                ('gs', models.CharField(blank=True, max_length=50, null=True)),
                ('mode_de_comparaison_des_besoin', models.CharField(blank=True, max_length=50, null=True)),
                ('int_ajust_amont', models.CharField(blank=True, max_length=50, null=True)),
                ('int_ajust_aval', models.CharField(blank=True, max_length=50, null=True)),
                ('taille_l_min', models.CharField(blank=True, max_length=50, null=True)),
                ('val_arrondie', models.CharField(blank=True, max_length=50, null=True)),
                ('taille_lot_mx', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_maximum', models.CharField(blank=True, max_length=50, null=True)),
                ('chant', models.CharField(blank=True, max_length=50, null=True)),
                ('typ', models.CharField(blank=True, max_length=50, null=True)),
                ('delai_sec', models.CharField(blank=True, max_length=50, null=True)),
                ('ctrl_destinataire', models.CharField(blank=True, max_length=50, null=True)),
                ('article_rempl', models.CharField(blank=True, max_length=50, null=True)),
                ('gml', models.CharField(blank=True, max_length=50, null=True)),
                ('grpl', models.CharField(blank=True, max_length=50, null=True)),
                ('abc', models.CharField(blank=True, max_length=50, null=True)),
                ('element_dOTP', models.CharField(blank=True, max_length=50, null=True)),
                ('grpa', models.CharField(blank=True, max_length=50, null=True)),
                ('Code_pilotage', models.CharField(blank=True, max_length=50, null=True)),
                ('hierarch_produits', models.CharField(blank=True, max_length=50, null=True)),
                ('poids_brut', models.CharField(blank=True, max_length=50, null=True)),
                ('poids_net', models.CharField(blank=True, max_length=50, null=True)),
                ('unp', models.CharField(blank=True, max_length=50, null=True)),
                ('pas_de_ccr', models.CharField(blank=True, max_length=50, null=True)),
                ('Taille_de_lot_du_CCR', models.CharField(blank=True, max_length=50, null=True)),
                ('uq', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lignemodifier',
            name='id_file',
        ),
        migrations.RemoveField(
            model_name='lignemodifier',
            name='ligne',
        ),
        migrations.RemoveField(
            model_name='mansour',
            name='id_file',
        ),
        migrations.DeleteModel(
            name='condition',
        ),
        migrations.DeleteModel(
            name='file',
        ),
        migrations.DeleteModel(
            name='lignemodifier',
        ),
        migrations.DeleteModel(
            name='mansour',
        ),
    ]
