# Generated by Django 4.1.7 on 2023-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0014_filems_remove_lignemodifier_id_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filems',
            old_name='uq',
            new_name='uq1',
        ),
        migrations.AddField(
            model_name='filems',
            name='uq2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filems',
            name='uq3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filems',
            name='uq4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filems',
            name='uq5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filems',
            name='uq6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filems',
            name='uq7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
