# Generated by Django 4.1.7 on 2023-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0015_rename_uq_filems_uq1_filems_uq2_filems_uq3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filems',
            old_name='unp',
            new_name='unp1',
        ),
        migrations.AddField(
            model_name='filems',
            name='unp2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
