# Generated by Django 4.1.7 on 2023-03-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0016_rename_unp_filems_unp1_filems_unp2'),
    ]

    operations = [
        migrations.AddField(
            model_name='filems',
            name='delai_sec1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filems',
            name='uq0',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
