# Generated by Django 4.1.7 on 2023-03-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0020_remove_file_fileid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filems',
            name='uq7',
        ),
    ]
