# Generated by Django 4.1.7 on 2023-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0021_remove_filems_uq7'),
    ]

    operations = [
        migrations.AddField(
            model_name='filems',
            name='uq7',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
