# Generated by Django 4.1.7 on 2023-03-22 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0022_filems_uq7'),
    ]

    operations = [
        migrations.AddField(
            model_name='filems',
            name='file_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profil.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
