# Generated by Django 4.1.7 on 2023-03-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0024_alter_filems_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
