# Generated by Django 4.1.7 on 2023-03-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0032_alter_filems_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
