# Generated by Django 4.1.7 on 2023-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0033_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filems',
            name='file_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
