# Generated by Django 4.1.7 on 2023-03-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0035_condition_resulta_rute_ligne_modifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rute',
            old_name='Vieux',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='field',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='id_ligne',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='nouveau',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='resulta_id',
        ),
        migrations.AlterField(
            model_name='rute',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
