# Generated by Django 4.1.7 on 2023-03-26 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0036_rename_vieux_rute_name_remove_rute_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulta',
            name='code_C',
        ),
        migrations.AddField(
            model_name='condition',
            name='id_rute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.rute'),
        ),
        migrations.AddField(
            model_name='resulta',
            name='id_rute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.rute'),
        ),
    ]
