# Generated by Django 4.1.7 on 2023-03-26 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0037_remove_resulta_code_c_condition_id_rute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulta',
            name='id_rute',
        ),
        migrations.AddField(
            model_name='resulta',
            name='code_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.condition'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='id_rute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.rute'),
        ),
    ]
