# Generated by Django 4.1.7 on 2023-03-26 02:17

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0038_remove_resulta_id_rute_resulta_code_c_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='code_N',
        ),
        migrations.AddField(
            model_name='condition',
            name='id',
            field=models.AutoField(default=builtins.id, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
