# Generated by Django 4.1.7 on 2023-03-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0039_remove_condition_code_n_condition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
