# Generated by Django 4.1.7 on 2023-03-26 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0040_alter_condition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulta',
            name='code_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.rute'),
        ),
        migrations.DeleteModel(
            name='condition',
        ),
    ]
