# Generated by Django 4.1.7 on 2023-03-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0041_alter_resulta_code_c_delete_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
