# Generated by Django 4.1.7 on 2023-03-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0043_remove_resulta_code_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resulta',
        ),
    ]
