# Generated by Django 4.1.7 on 2023-03-26 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0044_delete_resulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='condition',
            fields=[
                ('code_N', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('mot', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('mot', models.CharField(blank=True, max_length=50, null=True)),
                ('code_C', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.condition')),
            ],
        ),
    ]
