# Generated by Django 4.1.7 on 2023-03-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0045_condition_resulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rute',
            old_name='name',
            new_name='Vieux',
        ),
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='id_ligne',
        ),
        migrations.RemoveField(
            model_name='resulta',
            name='code_C',
        ),
        migrations.AddField(
            model_name='rute',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rute',
            name='nouveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
