# Generated by Django 4.1.7 on 2023-03-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0046_rename_name_rute_vieux_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='condition',
        ),
        migrations.DeleteModel(
            name='resulta',
        ),
        migrations.DeleteModel(
            name='rute',
        ),
    ]
