# Generated by Django 4.1.7 on 2023-04-12 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0048_rute_resulta_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resulta',
            name='id_rute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profil.condition'),
        ),
    ]
