# Generated by Django 4.1.7 on 2023-04-12 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0049_alter_resulta_id_rute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condition',
            old_name='mot',
            new_name='Con',
        ),
        migrations.RenameField(
            model_name='resulta',
            old_name='mot',
            new_name='Res',
        ),
    ]
