# Generated by Django 4.1.7 on 2023-04-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0050_rename_mot_condition_con_rename_mot_resulta_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resulta',
            old_name='id_rute',
            new_name='id_condition',
        ),
        migrations.AddField(
            model_name='ligne_modifier',
            name='id_rutee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.rute'),
        ),
    ]
