# Generated by Django 4.1.7 on 2023-04-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0051_rename_id_rute_resulta_id_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rute',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
