# Generated by Django 4.1.7 on 2023-04-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0052_rute_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rute',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
