# Generated by Django 4.1.7 on 2023-04-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0053_alter_rute_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_modifier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
