# Generated by Django 4.1.7 on 2023-04-18 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0054_ligne_modifier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_modifier',
            name='id_ligne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.filems'),
        ),
    ]
