# Generated by Django 4.1.7 on 2023-04-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0055_ligne_modifier_id_ligne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='id_ligne',
        ),
    ]
