# Generated by Django 4.1.7 on 2023-04-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0056_remove_ligne_modifier_id_ligne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='field',
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ligne_modifier',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ligne_modifier',
            name='id_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profil.filems'),
        ),
        migrations.AddField(
            model_name='rute',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='rute',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
