# Generated by Django 4.1.7 on 2023-04-19 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0057_remove_ligne_modifier_field_file_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligne_modifier',
            old_name='id_rutee',
            new_name='id_rute',
        ),
    ]
