# Generated by Django 4.1.7 on 2023-04-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0058_rename_id_rutee_ligne_modifier_id_rute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_updated',
        ),
    ]
