# Generated by Django 4.1.7 on 2023-04-19 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0059_remove_file_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
    ]
