# Generated by Django 4.1.7 on 2023-04-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0060_remove_file_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
