# Generated by Django 4.1.7 on 2023-04-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0061_file_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
    ]
