# Generated by Django 4.1.7 on 2023-04-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0063_file_timestamp_file_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='user',
            new_name='imported_by',
        ),
    ]
