# Generated by Django 4.1.7 on 2023-04-19 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0064_rename_user_file_imported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='imported_by',
        ),
    ]
