# Generated by Django 4.1.7 on 2023-04-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0065_remove_file_imported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='imported_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
