# Generated by Django 4.1.7 on 2023-04-19 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0066_file_imported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='ligne_modifier',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ligne_modifier',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rute',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rute',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
