# Generated by Django 4.1.7 on 2023-04-19 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0067_remove_ligne_modifier_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligne_modifier',
            old_name='timestamp',
            new_name='date',
        ),
    ]
