# Generated by Django 4.1.7 on 2023-04-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0068_rename_timestamp_ligne_modifier_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rute',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='rute',
            old_name='user',
            new_name='imported_by',
        ),
    ]
