# Generated by Django 4.1.7 on 2023-04-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0069_rename_timestamp_rute_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rute',
            name='imported_by',
        ),
    ]
