# Generated by Django 4.1.7 on 2023-04-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0071_remove_rute_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rute',
            name='imported_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rute',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
