# Generated by Django 4.1.7 on 2023-04-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0072_rute_imported_by_rute_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='id_rute',
        ),
    ]
