# Generated by Django 4.1.7 on 2023-04-19 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0073_remove_ligne_modifier_id_rute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rute',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='rute',
            name='updated',
        ),
    ]
