# Generated by Django 4.1.7 on 2023-04-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0074_remove_rute_date_remove_rute_imported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rute',
            name='imported_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
