# Generated by Django 4.1.7 on 2023-04-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0076_rute_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rute',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
