# Generated by Django 4.1.7 on 2023-04-19 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0077_rute_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rute',
            name='updated',
        ),
    ]
