# Generated by Django 4.1.7 on 2023-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0078_remove_rute_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rute',
            name='data_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
