# Generated by Django 4.1.7 on 2023-04-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0081_remove_ligne_modifier_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_modifier',
            name='id_file',
        ),
    ]
