# Generated by Django 4.1.7 on 2023-04-19 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0083_ligne_modifier_id_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_modifier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
