# Generated by Django 4.1.7 on 2023-04-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0085_ligne_modifier_id_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_modifier',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
