# Generated by Django 4.1.7 on 2023-04-20 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0091_ligne_modifier_id_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_modifier',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
