# Generated by Django 4.1.7 on 2023-04-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0093_remove_ligne_modifier_vieux_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligne_modifier',
            old_name='field',
            new_name='idd',
        ),
    ]
