# Generated by Django 4.1.7 on 2023-04-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0094_rename_field_ligne_modifier_idd'),
    ]

    operations = [
        migrations.CreateModel(
            name='lignemodifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ligne_modifier',
        ),
    ]
