# Generated by Django 4.1.7 on 2023-04-21 04:04

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0095_lignemodifier_delete_ligne_modifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemodifier',
            name='id_condition',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='profil.condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignemodifier',
            name='id_ligne',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='profil.filems'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lignemodifier',
            name='nouveau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lignemodifier',
            name='vieux',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
