# Generated by Django 4.1.7 on 2023-04-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0099_lignemodifier_delete_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignemodifier',
            name='id_condition',
        ),
    ]
