# Generated by Django 4.1.7 on 2023-04-21 05:45

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0101_remove_lignemodifier_id_ligne'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemodifier',
            name='id_condition',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='profil.condition'),
            preserve_default=False,
        ),
    ]
