# Generated by Django 4.1.7 on 2023-04-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0102_lignemodifier_id_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignemodifier',
            name='vieux',
        ),
    ]
