# Generated by Django 4.1.7 on 2023-04-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0103_remove_lignemodifier_vieux'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignemodifier',
            name='nouveau',
        ),
    ]
