# Generated by Django 4.1.7 on 2023-04-21 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0104_remove_lignemodifier_nouveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignemodifier',
            name='id_condition',
        ),
    ]
